import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import {
  AlertCircle,
  AlertTriangleIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowUpRightIcon,
  Blocks,
  BookIcon,
  BookmarkIcon,
  BotIcon,
  BrainIcon,
  CalendarIcon,
  CameraIcon,
  CheckCircle2Icon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronsUpDownIcon,
  CircleDotIcon,
  CircleIcon,
  ClipboardCheckIcon,
  ClipboardListIcon,
  ClockIcon,
  Code,
  CopyIcon,
  CornerDownLeftIcon,
  DotIcon,
  DownloadIcon,
  EditIcon,
  Expand,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FileIcon,
  FileTextIcon,
  FilterIcon,
  FolderOpenIcon,
  GitCommitIcon,
  GlobeIcon,
  GripVerticalIcon,
  ImageIcon,
  InfoIcon,
  KeyRoundIcon,
  ListChecksIcon,
  Loader2Icon,
  LockIcon,
  LogInIcon,
  LogOutIcon,
  MailIcon,
  MessageCircleIcon,
  MicIcon,
  Minimize2,
  MinusIcon,
  MonitorIcon,
  MoonIcon,
  MoreHorizontalIcon,
  Music2Icon,
  PackageIcon,
  PanelLeftCloseIcon,
  PanelLeftOpenIcon,
  PaperclipIcon,
  PauseIcon,
  PhoneIcon,
  PlayIcon,
  PlusIcon,
  RotateCwIcon,
  SaveIcon,
  SearchIcon,
  Settings2Icon,
  SettingsIcon,
  SlashIcon,
  SparklesIcon,
  Square,
  SquareIcon,
  StarIcon,
  SunIcon,
  TerminalIcon,
  TrashIcon,
  UploadIcon,
  UserIcon,
  VideoIcon,
  WrenchIcon,
  XCircleIcon,
  XIcon,
  ZapIcon,
  type LucideIcon,
} from "@/lib/icons";

const meta = {
  title: "Global/Icons",
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

const MATERIAL_ICONS: [LucideIcon, string][] = [
  [AlertCircle, "AlertCircle"],
  [AlertTriangleIcon, "AlertTriangleIcon"],
  [ArrowDownIcon, "ArrowDownIcon"],
  [ArrowLeftIcon, "ArrowLeftIcon"],
  [ArrowRightIcon, "ArrowRightIcon"],
  [ArrowUpIcon, "ArrowUpIcon"],
  [ArrowUpRightIcon, "ArrowUpRightIcon"],
  [CalendarIcon, "CalendarIcon"],
  [CameraIcon, "CameraIcon"],
  [CheckIcon, "CheckIcon"],
  [ChevronDownIcon, "ChevronDownIcon"],
  [ChevronLeftIcon, "ChevronLeftIcon"],
  [ChevronRightIcon, "ChevronRightIcon"],
  [ChevronUpIcon, "ChevronUpIcon"],
  [ChevronsUpDownIcon, "ChevronsUpDownIcon"],
  [CopyIcon, "CopyIcon"],
  [CornerDownLeftIcon, "CornerDownLeftIcon"],
  [DownloadIcon, "DownloadIcon"],
  [EditIcon, "EditIcon"],
  [Expand, "Expand"],
  [ExternalLinkIcon, "ExternalLinkIcon"],
  [EyeIcon, "EyeIcon"],
  [EyeOffIcon, "EyeOffIcon"],
  [FileIcon, "FileIcon"],
  [FileTextIcon, "FileTextIcon"],
  [FilterIcon, "FilterIcon"],
  [FolderOpenIcon, "FolderOpenIcon"],
  [GlobeIcon, "GlobeIcon"],
  [GripVerticalIcon, "GripVerticalIcon"],
  [ImageIcon, "ImageIcon"],
  [InfoIcon, "InfoIcon"],
  [KeyRoundIcon, "KeyRoundIcon"],
  [Loader2Icon, "Loader2Icon"],
  [LockIcon, "LockIcon"],
  [LogInIcon, "LogInIcon"],
  [LogOutIcon, "LogOutIcon"],
  [MailIcon, "MailIcon"],
  [MicIcon, "MicIcon"],
  [Minimize2, "Minimize2"],
  [MinusIcon, "MinusIcon"],
  [MonitorIcon, "MonitorIcon"],
  [MoonIcon, "MoonIcon"],
  [MoreHorizontalIcon, "MoreHorizontalIcon"],
  [PanelLeftCloseIcon, "PanelLeftCloseIcon"],
  [PanelLeftOpenIcon, "PanelLeftOpenIcon"],
  [PaperclipIcon, "PaperclipIcon"],
  [PhoneIcon, "PhoneIcon"],
  [PlusIcon, "PlusIcon"],
  [RotateCwIcon, "RotateCwIcon"],
  [SaveIcon, "SaveIcon"],
  [SearchIcon, "SearchIcon"],
  [Settings2Icon, "Settings2Icon"],
  [SettingsIcon, "SettingsIcon"],
  [SquareIcon, "SquareIcon"],
  [SunIcon, "SunIcon"],
  [TerminalIcon, "TerminalIcon"],
  [TrashIcon, "TrashIcon"],
  [UploadIcon, "UploadIcon"],
  [UserIcon, "UserIcon"],
  [XIcon, "XIcon"],
];

const LUCIDE_ICONS: [LucideIcon, string][] = [
  [Blocks, "Blocks"],
  [BookIcon, "BookIcon"],
  [BookmarkIcon, "BookmarkIcon"],
  [BotIcon, "BotIcon"],
  [BrainIcon, "BrainIcon"],
  [CheckCircle2Icon, "CheckCircle2Icon"],
  [CheckCircleIcon, "CheckCircleIcon"],
  [CircleDotIcon, "CircleDotIcon"],
  [CircleIcon, "CircleIcon"],
  [ClipboardCheckIcon, "ClipboardCheckIcon"],
  [ClipboardListIcon, "ClipboardListIcon"],
  [ClockIcon, "ClockIcon"],
  [Code, "Code"],
  [DotIcon, "DotIcon"],
  [GitCommitIcon, "GitCommitIcon"],
  [ListChecksIcon, "ListChecksIcon"],
  [MessageCircleIcon, "MessageCircleIcon"],
  [Music2Icon, "Music2Icon"],
  [PackageIcon, "PackageIcon"],
  [PauseIcon, "PauseIcon"],
  [PlayIcon, "PlayIcon"],
  [SlashIcon, "SlashIcon"],
  [SparklesIcon, "SparklesIcon"],
  [Square, "Square"],
  [StarIcon, "StarIcon"],
  [VideoIcon, "VideoIcon"],
  [WrenchIcon, "WrenchIcon"],
  [XCircleIcon, "XCircleIcon"],
  [ZapIcon, "ZapIcon"],
];

export const MaterialSymbols: Story = {
  render: () => <IconGrid icons={MATERIAL_ICONS} />,
};

export const Lucide: Story = {
  render: () => <IconGrid icons={LUCIDE_ICONS} />,
};

function IconGrid({ icons }: { icons: [LucideIcon, string][] }) {
  return (
    <div className="grid grid-cols-[repeat(auto-fill,minmax(96px,1fr))] gap-2">
      {icons.map(([IconComponent, label]) => (
        <div
          key={label}
          className="flex flex-col items-center gap-1.5 rounded-lg border border-border bg-card p-3"
        >
          <IconComponent className="size-6 text-foreground" />
          <span className="w-full truncate text-center font-mono text-[9px] leading-tight text-muted-foreground">
            {label}
          </span>
        </div>
      ))}
    </div>
  );
}
