import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import type { TmsAccess } from "../prompt/testomatio.js";
import { PI_STATE_DIR } from "./env.js";

const require_ = createRequire(import.meta.url);

export const SERVER = "testomatio";

/**
 * Promoted to their own tools instead of going through the proxy: the reads the
 * skills reach for constantly. @testomatio/mcp exposes 90 tools and registering
 * them all would cost roughly 15k tokens of system prompt, which is the bloat
 * the proxy exists to avoid. Everything else stays reachable through `mcp`.
 */
export const DIRECT_TOOLS = [
  "tests_list",
  "tests_get",
  "tests_search",
  "suites_list",
  "suites_get",
  "runs_list",
  "runs_get",
  "testruns_list",
  "plans_list",
  "plans_get",
  "labels_list",
];

/** No project token means no Testomat.io tools at all, so the prompt must say so. */
export function tmsAccess(): TmsAccess {
  if (!process.env.TESTOMATIO) return "cli-only";
  return "mcp-proxy";
}

export function hasTestomatio(): boolean {
  return Boolean(process.env.TESTOMATIO);
}

/**
 * An in-memory server definition built from the environment. Deliberately not
 * discovered from the checkout: a CI clone must not be able to point the agent
 * at an MCP server of its own.
 */
export function mcpConfig(): McpConfig {
  return {
    mcpServers: {
      [SERVER]: {
        command: process.execPath,
        args: [require_.resolve("@testomatio/mcp/index.js")],
        env: {
          TESTOMATIO: process.env.TESTOMATIO ?? "",
          TESTOMATIO_URL: process.env.TESTOMATIO_URL ?? "",
        },
        lifecycle: "lazy",
        directTools: DIRECT_TOOLS,
      },
    },
  };
}

export function metadataCachePath(): string {
  return join(PI_STATE_DIR, "mcp-cache.json");
}

/**
 * Direct tools are registered from the adapter's metadata cache, which does not
 * exist on a fresh CI runner — so a first run would degrade to proxy-only. The
 * tool metadata ships with this package (generated by `bunosh mcp:seed` from
 * @testomatio/mcp's own definitions), and this writes it as a cache entry.
 *
 * The entry is keyed by a hash of the resolved server definition, so the hash
 * has to come from the adapter itself rather than a copy of its logic. That
 * module is raw TypeScript reached by absolute path, which only works from
 * inside pi's jiti-loaded extension — see mcp-extension.ts. A failure here is
 * not fatal: the run continues proxy-only, which still works.
 */
export async function seedMetadataCache(config: McpConfig): Promise<void> {
  const cachePath = metadataCachePath();
  if (existsSync(cachePath)) return;

  const tools = readSeedTools();
  if (tools.length === 0) return;

  const hash = await computeServerHash(config.mcpServers[SERVER]);
  if (!hash) return;

  const cache = {
    version: 1,
    servers: {
      [SERVER]: {
        configHash: hash,
        tools,
        resources: [],
        cachedAt: Date.now(),
      },
    },
  };
  mkdirSync(PI_STATE_DIR, { recursive: true });
  writeFileSync(cachePath, `${JSON.stringify(cache, null, 2)}\n`, "utf8");
}

function readSeedTools(): SeedTool[] {
  const path = join(import.meta.dirname, "..", "..", "mcp-tools.json");
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return [];
  }
}

async function computeServerHash(definition: unknown): Promise<string | null> {
  try {
    const adapter = require_.resolve("pi-mcp-adapter");
    const module = await import(join(dirname(adapter), "metadata-cache.ts"));
    return module.computeServerHash(definition);
  } catch {
    return null;
  }
}

export interface SeedTool {
  name: string;
  description?: string;
  inputSchema?: unknown;
}

export interface McpConfig {
  mcpServers: Record<string, Record<string, unknown>>;
}
